.PHONY: clean All

All:
	@echo "----------Building project:[ oracle_connect - Debug ]----------"
	@cd "oracle_connect" && "$(MAKE)" -f  "oracle_connect.mk"
clean:
	@echo "----------Cleaning project:[ oracle_connect - Debug ]----------"
	@cd "oracle_connect" && "$(MAKE)" -f  "oracle_connect.mk" clean
